package com.pwr.bdprojekt.gui.displays;

public enum ViewType {
	HOME_ADMIN_TECH,
	HOME,
	ADDRESS_EDITOR,
	ATTRACTION_EDITOR,
	LOCALITY_EDITOR,
	PERMISSION_EDITOR,
	PERMISSION_REGION_EDITOR,
	LOCALITY_FILTER,
	USERS_FILTER,
	LOCALITY_LIST_ADMIN_MERIT,
	LOCALITY_LIST,
	USERS_LIST,
	LOGIN,
	ASSIGN_ATTRACTION,
	ASSIGN_ADDRESS,
	ASSIGN_FIGURE,
	LOCALITY_SORT,
	USERS_SORT,
	LOCALITY_DATA,
	LOCALITY_DATA_ADMIN_MERIT,
	USER_DATA_ADMIN_TECH,
	USER_DATA,
	NONE
}