INSERT INTO attraction_types (
	`name`
) VALUES
('zamek'),
('góra'),
('plaża'),
('muzeum'),
('park narodowy'),
('jezioro'),
('trasa rowerowa'),
('skansen'),
('wieżowiec'),
('park rozrywki'),
('jaskinia'),
('ogród botaniczny'),
('restauracja'),
('pomnik'),
('park linowy'),
('wodospad'),
('trasa narciarska'),
('stadion'),
('przystań'),
('skocznia narciarska'),
('centrum handlowe'),
('zabytek'),
('park dinozaurów'),
('zoo'),
('park'),
('teatr'),
('termy'),
('port'),
('sanktuarium'),
('nekropolia'),
('mauzoleum'),
('szlak kajakowy'),
('skwer miejski'),
('kolejki'),
('spa'),
('tor go-kartowy'),
('pole golfowe'),
('pub'),
('stadnina koni'),
('centrum edukacyjne'),
('pałac'),
('hotel'),
('zajazd'),
('zakwaterowanie'),
('agroturystyka'),
('punkt widokowy'),
('bar'),
('przyroda'),
('kościół'),
('sztuka'),
('historia'),
('w środku'),
('na zewnątrz'),
('las'),
('akwen'),
('gastronomia'),
('uzdrowisko'),
('starówka'),
('sklep'),
('galeria sztuki'),
('sport');